// Auth
export const LOGIN_START = "LOGIN_START";
export const LOGIN_STOP = "LOGIN_STOP";
// Users
export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_STOP = "FETCH_USERS_STOP";
// Invoices Network Operations
export const FETCH_INVOICES_START = "FETCH_INVOICES_START";
export const FETCH_INVOICES_STOP = "FETCH_INVOICES_STOP";
export const FETCH_INVOICE_START = "FETCH_INVOICE_START";
export const FETCH_INVOICE_STOP = "FETCH_INVOICE_STOP";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
// Invoice Modes
export const DELETE_ITEM = "DELETE_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";
export const MOVE_TO_CREATE_NEW_INVOICE_MODE = "MOVE_TO_CREATE_NEW_INVOICE_MODE";
export const MOVE_TO_EDIT_INVOICE_MODE = "MOVE_TO_EDIT_INVOICE_MODE";
export const ADD_ITEM_TO_INVOICE = "ADD_ITEM_TO_INVOICE";
export const UPDATE_CURRENT_INVOICE_ITEM = "UPDATE_CURRENT_INVOICE_ITEM";
export const UPDATE_CURRENT_INVOICE_LIST_ITEM = "UPDATE_CURRENT_INVOICE_LIST_ITEM";
