// Auth
export const LOGIN_START = "LOGIN_START";
export const LOGIN_STOP = "LOGIN_STOP";
// Users
export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_STOP = "FETCH_USERS_STOP";
// Invoices
export const FETCH_INVOICES_START = "FETCH_INVOICES_START";
export const FETCH_INVOICES_STOP = "FETCH_INVOICES_STOP";
export const FETCH_INVOICE_START = "FETCH_INVOICE_START";
export const FETCH_INVOICE_STOP = "FETCH_INVOICE_STOP";
export const CREATE_NEW_INVOICE = "CREATE_NEW_INVOICE";
export const EDIT_INVOICE = "EDIT_INVOICE";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
